#!/usr/bin/env python

#		pyzgoubi - python interface to zgoubi
#		Copyright 2008 - 2009 Sam Tygier <Sam.Tygier@hep.manchester.ac.uk>
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.


from __future__ import division
from math import *
import getopt, sys, os
import subprocess
from zgoubi.utils import *
from zgoubi.core import *
from zgoubi.constants import *
from zgoubi.version import *
from zgoubi.bunch import *

sys.path.append(os.getcwd())

# create a set of functions that work on default_line and default_results objects
# these will make it simpler to run simple simulations

def make_line(*a, **k):
	global default_line
	default_line = Line(*a, **k)

def run(*a, **k):
	global default_line, default_result
	default_result = default_line.run(*a, **k)
	return default_result

# most of these functions can be built from a template

function_template="""def %(func_name)s(*a, **k):
	global default_%(class_name)s
	return default_%(class_name)s.%(func_name)s(*a, **k)
"""
# templatable functions for the line class
line_funcs = ['add', 'output', 'full_tracking', 'remove_looping', 'add_input_files', 'replace']

for func_name in line_funcs:
	code = function_template%dict(func_name=func_name, class_name='line')
	exec(code)

# templatable functions for the res class

# this pattern builds all the file access functions by pattern
res_funcs = [a%b for a in ['%s_fh', '%s', 'save_%s'] for b in ['res', 'fai', 'dat', 'plt', 'b_fai']]

res_funcs += ['get_all', 'get_track', 'get_tune', 'get_twiss_parameters', 'run_success']

for func_name in res_funcs:
	code = function_template%dict(func_name=func_name, class_name='result')
	exec(code)

def _show_help(help_arg):
	if help_arg == None:
		print "For documentation see http://www.hep.manchester.ac.uk/u/sam/pyzgoubi/"
		sys.exit(0)
	if help_arg.lower() == "elements":
		print "available elements"
		elements = []

		for k,v in globals().items():
			try:
				if issubclass(v, zgoubi_element):
					if not k in ['zgoubi_element','zgoubi_particul']:
						elements.append(k)
			except TypeError:
				pass
		elements.sort()
		print '\n'.join(elements)
		sys.exit(0)

	try:
		help_elem = globals()[help_arg.upper()]
	except KeyError:
		print "There is no help for %s"%sys.argv[2]
		sys.exit(1)

	print help_arg.upper()
	help_elem_inst = eval("%s()"%help_arg.upper())
	print "zgoubi name:",help_elem_inst._zgoubi_name
	print "Parameters:"
	print '\n'.join(help_elem_inst.list_params())

def _show_usage():
	print "Usage:"
	print sys.argv[0], "input_file_name"
	print sys.argv[0], "--help"


if __name__ == '__main__':
	try:
		opts, args = getopt.getopt(sys.argv[1:], "h", ["help", "version", "zgoubi="])
	except getopt.GetoptError, err:
		print str(err)
		_show_usage()
		sys.exit(1)

	if len(sys.argv) == 1:
		_show_usage()
		sys.exit(1)

	for o, a in opts:
		if o in ['--version']:
			print "Pyzgoubi version: %s"%MAIN_VERSION
			try:
				print 'Bzr: %(branch_nick)s rev %(revno)d' % version_info
			except NameError:
				pass
			print "Zgoubi path", zgoubi_settings['zgoubi_path']
			output = subprocess.Popen([zgoubi_settings['zgoubi_path']], stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()[0]
			for line in output.split('\n'):
				if "version" in line.lower():
					print line.strip()
			sys.exit(0)
		if o in ['--help', "-h"]:
			if len(args):
				_show_help(args[0])
			else:
				_show_help(None)
			sys.exit(0)
		if o in ['--zgoubi']:
			 zgoubi_settings['zgoubi_path'] = a
	try:
		input_file_name = args[0]
	except IndexError:
		print "No input file, try:"
		print "pyzgoubi inputfile"
		sys.exit(1)
	
	if not os.path.exists(input_file_name):
		print "no such input file in current directory"
		sys.exit(1)
		
	execfile(input_file_name)
	

	for left_over in locals().values():
		if "Line"  in str(type(left_over)).split("'")[1]:
			del(left_over)




